### ISSUE TITLE
Authentication header field

### ISSUE THREAD

**Issue by ghost** [mtschirs/quizduellapi#7]
Hi. I want to develop PHP API for this game and I have successfully sniffed all app requests so I know format, but there is one problem.
Every request has Authentication field in header. I'm using Russian version of the game (https://play.google.com/store/apps/details?id=se.feomedia.quizkampen.ru.lite) and I have smali code which is obfuscated but I had enough experience to even write a cheat for this game, I injected my code and made every answer correct (just for fun, not for cheating :joy:) but I don't actually know how to get Authentication generation algorithm. 
I saw that you have function which generates Authentication code so maybe you can explain how you write it?
Thank you in advance.

**Comment by mtschirs** [comment]
Hi Max-Stern,

have a look at the two class methods __scramble_authorization_code_ and __get_authorization_code_. You will see how the authorization code is build step by step. If you don't understand a specific line of python code, feel free to reopen this issue and ask again.
